language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

env:
  - RAILS_VERSION=4.2
  - RAILS_VERSION=5.0
  - RAILS_VERSION=5.1

matrix:
  exclude:
    - rvm: 2.2
      env: RAILS_VERSION=5.0
    - rvm: 2.2
      env: RAILS_VERSION=5.1
  allow_failures:
    - rvm: 2.5

sudo: false
